import { useState } from "react";
import {
  DocumentTextIcon,
  ClipboardIcon,
  CheckIcon,
  ArrowDownTrayIcon,
} from "@heroicons/react/24/outline";

const DocumentDisplay = ({ document }) => {
  const [copied, setCopied] = useState(false);

  if (!document) return null;

  const handleCopy = () => {
    navigator.clipboard.writeText(document);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([document], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = window.document.createElement("a");
    a.href = url;
    a.download = "LawSarthi_Legal_Document.txt";
    a.click();
    URL.revokeObjectURL(url);
  };

  const formatDocument = (text) => {
    const sections = text.split("\n\n");

    return sections.map((section, index) => {
      if (
        section.includes("LEGAL COMPLAINT") ||
        section.includes("To,") ||
        section.includes("Parties Involved:") ||
        section.includes("Factual Summary:") ||
        section.includes("Applicable Legal Sections:") ||
        section.includes("Demand or Request:") ||
        section.includes("Date:") ||
        section.includes("Sender Details:")
      ) {
        const [title, ...content] = section.split("\n");
        return (
          <div key={index} className="mb-6">
            <h3
              className="text-base font-black mb-2 pb-1"
              style={{
                color: "#1a1a2e",
                borderBottom: "2px solid #c9a84c44",
                fontFamily: "'Georgia', serif",
                letterSpacing: "0.3px",
              }}
            >
              {title}
            </h3>
            {content.length > 0 && (
              <div
                className="whitespace-pre-line pl-4 leading-relaxed"
                style={{
                  color: "#374151",
                  fontFamily: "system-ui, sans-serif",
                  fontSize: "0.92rem",
                }}
              >
                {content.join("\n")}
              </div>
            )}
          </div>
        );
      }

      return (
        <div
          key={index}
          className="mb-4 whitespace-pre-line leading-relaxed"
          style={{
            color: "#374151",
            fontFamily: "system-ui, sans-serif",
            fontSize: "0.92rem",
          }}
        >
          {section}
        </div>
      );
    });
  };

  return (
    <div
      className="rounded-2xl p-8"
      style={{
        background: "white",
        border: "1px solid #c9a84c33",
        boxShadow: "0 4px 40px rgba(201,168,76,0.08)",
        fontFamily: "'Georgia', 'Times New Roman', serif",
      }}
    >
      {/* Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 mb-6">
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-lg" style={{ background: "#1a1a2e" }}>
            <DocumentTextIcon
              className="h-5 w-5"
              style={{ color: "#c9a84c" }}
            />
          </div>
          <div>
            <h2
              className="text-2xl font-black text-gray-900"
              style={{ fontFamily: "'Georgia', serif" }}
            >
              Your Legal Document
            </h2>
            <p
              className="text-xs text-gray-400"
              style={{ fontFamily: "system-ui, sans-serif" }}
            >
              Generated by LawSarthi AI • Review before submission
            </p>
          </div>
        </div>

        {/* Action buttons */}
        <div className="flex items-center gap-3">
          <button
            onClick={handleDownload}
            className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold transition-all duration-200 hover:opacity-90"
            style={{
              background: "#1a1a2e",
              color: "#c9a84c",
              border: "1px solid #c9a84c44",
              fontFamily: "system-ui, sans-serif",
            }}
          >
            <ArrowDownTrayIcon className="h-4 w-4" />
            Download
          </button>

          <button
            onClick={handleCopy}
            className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold transition-all duration-200 hover:opacity-90"
            style={{
              background: copied ? "#f0fdf4" : "#fdfaf5",
              color: copied ? "#16a34a" : "#374151",
              border: `1px solid ${copied ? "#86efac" : "#c9a84c44"}`,
              fontFamily: "system-ui, sans-serif",
            }}
          >
            {copied ? (
              <>
                <CheckIcon className="h-4 w-4 text-green-600" />
                Copied!
              </>
            ) : (
              <>
                <ClipboardIcon className="h-4 w-4" />
                Copy
              </>
            )}
          </button>
        </div>
      </div>

      {/* Divider */}
      <div
        className="h-px w-full mb-6"
        style={{
          background:
            "linear-gradient(90deg, #c9a84c44, #4f8ef722, transparent)",
        }}
      />

      {/* Document body */}
      <div
        className="rounded-xl p-8"
        style={{
          background: "#fdfaf5",
          border: "1px solid #e8e0d0",
          minHeight: "300px",
        }}
      >
        {/* Watermark header */}
        <div
          className="flex items-center justify-between mb-6 pb-4"
          style={{ borderBottom: "1px dashed #c9a84c55" }}
        >
          <span
            className="text-xs uppercase tracking-widest font-bold"
            style={{ color: "#c9a84c99", fontFamily: "system-ui, sans-serif" }}
          >
            LawSarthi — Legal Document Draft
          </span>
          <span
            className="text-xs"
            style={{ color: "#c9a84c99", fontFamily: "system-ui, sans-serif" }}
          >
            {new Date().toLocaleDateString("en-IN", {
              day: "numeric",
              month: "long",
              year: "numeric",
            })}
          </span>
        </div>

        <div className="prose max-w-none">{formatDocument(document)}</div>
      </div>

      {/* Disclaimer */}
      <div
        className="mt-6 rounded-xl p-4 flex items-start gap-3"
        style={{
          background: "#1a1a2e08",
          border: "1px solid #c9a84c33",
          fontFamily: "system-ui, sans-serif",
        }}
      >
        <span style={{ color: "#c9a84c", fontSize: "1.1rem" }}>⚖️</span>
        <p className="text-xs leading-relaxed" style={{ color: "#6b7280" }}>
          <strong style={{ color: "#1a1a2e" }}>Disclaimer:</strong> This
          document is generated by LawSarthi AI and serves as a draft template
          based on your provided information. Please have it reviewed by a
          qualified legal professional before formal submission.
        </p>
      </div>
    </div>
  );
};

export default DocumentDisplay;
